import type { Metadata } from "next";
import "./globals.css";
import connect from "@/db/db";
connect();

export const metadata: Metadata = {
  title: "StudyPal",
  description: "Generated by Vibe Coder :)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">{children}</body>
    </html>
  );
}
