import type { Metadata } from "next";
import "./globals.css";
import connect from "@/db/db";
import Navbar from "@/components/navbar";
connect();

export const metadata: Metadata = {
  title: "StudyPal",
  description: "Generated by Vibe Coder :)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark scrollbar-hide">
        <Navbar />
        <main className="mt-20 ">{children}</main>
      </body>
    </html>
  );
}
